### ISSUE TITLE
Add JSON front-matter support

### ISSUE THREAD

**Issue by mauvm** [mauvm/documark#10]
Personally I prefer tabs instead of spaces. The YAML front-matter [does not support tabs](http://www.yaml.org/faq.html) as indentation. Since JSON is widely known due to its closeness to Javascript we should support JSON front-matter (FYI `JSON = JavaScript Object Notation`).

``` json
;;;
"layout": "custom",
"my_list": [
    "one",
    "two",
    "three"
]
;;;
```

The `;;;` make this feature backwards compatible, although I'm not very fond of it.. We could also use `---` and check for `"` as first (non-whitespace) character.

Also see: https://middlemanapp.com/basics/frontmatter/

**Comment by jeroenkruis** [comment]
I definitely agree about the JSON part. What about a separate JSON file. See npm's `package.json` as an example. You might also want to take plugin configuration in consideration, an external JSON file would be a good place to include those settings as well.

If a document contains a lot of options, plugins and other settings the main file (document.jade) would be cluttered with document configuration, instead of context.

Also i'm not very keen about using `;;;`

**Comment by mauvm** [comment]
That is already a possibility, place a `config.json` file next to your `document.jade` and remote the document's front-matter.

The support for front-matter is for basic and same-file configuration. The latter is to support sharing a single file (`document.jade`) for the entire document. That is: configuration, structure, and content.

Also see: https://github.com/documark/documark#configuration

**Comment by mauvm** [comment]
Coffeescript Object Notation would also be an option: https://www.npmjs.com/package/cson

**Comment by mauvm** [comment]
The library for parsing the front matter has now been changed to [gray matter](https://github.com/jonschlinkert/gray-matter), which supports multiple languages: YAML, JSON, and TOML. Use it like this:

```
---json
{
    "filename": "Document.pdf",
    "title": "Title",
    "version": "0.1",
    "plugins": [
        "dmp-theme-default"
    ],
    "chapterNumbering": {
        "depth": 2
    },
    "debug": true
}
---
```
