### ISSUE TITLE
Theme naming convention

### ISSUE THREAD

**Issue by jeroenkruis** [mauvm/documark#6]
Add a section to the README.md about theme naming conventions.
I think the first option is the best, what do you think?
1. `dmp-theme-mytheme`
2. `documark-theme-mytheme`
3. `dmp-mytheme`

**Comment by MalcolmK** [comment]
I think the second. But I wouldn't mind if it were the first.

**Comment by jeroenkruis** [comment]
Plugins for Documark are called `dmp-myplugin`. So it would make sense naming theme's `dmp-mytheme` or `dmp-theme-mytheme`.

**Comment by MalcolmK** [comment]
Fair enough.

**Comment by mauvm** [comment]
Good point! I prefer `dmp-theme-mytheme`, so that themes are prefixed with `dmp-theme-`.

This is also why I named the default theme `documark-theme-default`, instead of `default-theme`. I still have to change the prefix to `dmp-` though.

Alternatively `dmt-` would be an option (short for `documark theme`), but since it's loaded as a plugin I think option 1 is best. Also `dmp` and `dmt` are easy to confuse.
